### ISSUE TITLE
Get to square 0

### ISSUE THREAD

**Issue by mexindian** [ACDIVOCATech/easyNetworkMaker#2]
Push Dani's changes to repo

**Comment by mexindian** [comment]
looking good Dani!

Should I provide you feedback on every iteration? Or should I wait till our weekly's?

Quick one though... how come you switched to `require(visNetwork)` rather than `library()`?

**Comment by dani-tr** [comment]
I'd say weekly's - but happy to do per iteration as well. 

I think that one slipped in merging the two code bases - will switch to `library()`
